# Generated by Django 5.1.1 on 2024-10-16 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_sportevent_studentlist'),
        ('facultyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('AOOP', 'ADVANCED Object-Oriented Programming'), ('PFSD', 'Python Full Stack Development'), ('DBMS', 'Database Management System'), ('LAA', 'Linux Administration')], max_length=50)),
                ('section', models.CharField(choices=[('S11', 'Section-11'), ('S12', 'Section-12'), ('S13', 'Section-13'), ('S14', 'Section-14'), ('S15', 'Section-15')], max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.studentlist')),
            ],
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
